backend:
  #  name: test-repo
  #  name: git-gateway
  #  branch: master
  name: github
  repo: orkisz/przedszkole-site

locale: pl

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: dswesmbkz
    api_key: 145566431588812
    multiple: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: 'title'
        widget: 'string'
      - label: 'Data publikacji'
        name: 'date'
        widget: 'datetime'
      - label: 'Treść'
        name: 'body'
        widget: 'markdown'
      - label: 'Obraz'
        name: 'images'
        widget: 'image'
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true

  - name: 'group'
    label: 'Grupa'
    folder: 'content/group'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{order}}/index'
    editor:
      preview: false
    fields:
      - label: 'Nazwa grupy'
        name: 'name'
        widget: 'string'
      - label: 'Opis (pierwszy paragraf 2-3 zdania na stronę główną)'
        name: 'body'
        widget: 'markdown'
        modes:
          - raw
      - label: 'Obrazek - miniaturka'
        name: 'image'
        widget: 'image'
        required: true
      - label: 'Zdjęcie'
        name: 'photo'
        widget: 'image'
        required: true
      - label: 'Nr porządkowy'
        name: 'order'
        widget: 'number'
        value_type: 'int'
        min: 1
        max: 3
        required: true

  - name: 'galleryItem'
    label: 'Galeria'
    folder: 'content/gallery'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - label: 'Tytuł'
        name: 'title'
        widget: 'string'
      - label: 'Data publikacji'
        name: 'date'
        widget: 'datetime'
      - label: 'Obrazy'
        name: 'imagesList'
        widget: 'list'
        summary: '{{fields.image}}'
        field: { label: 'Obraz', name: image, widget: image }

  - name: 'pages'
    label: 'Strony specjalne'
    files:
      - name: 'personnel'
        label: 'Kadra'
        file: 'content/pages/personnel.yml'
        fields:
          - name: 'person'
            label: 'Osoba'
            widget: 'list'
            summary: '{{fields.name}}'
            fields:
              - name: 'name'
                label: 'Imię i nazwisko'
                widget: 'string'
              - name: 'description'
                label: 'Opis'
                widget: 'text'
              - name: 'role'
                label: 'Rola'
                widget: 'string'
              - name: 'photo'
                label: 'Zdjęcie'
                widget: 'image'
                required: false
      - name: 'events'
        label: 'Wydarzenia'
        file: 'content/pages/events.yml'
        fields:
          - name: 'event'
            label: 'Wydarzenie'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - name: 'title'
                label: 'Nazwa wydarzenia'
                widget: 'string'
              - name: 'start'
                label: 'Data rozpoczęcia'
                widget: 'datetime'
                default: ''
                date_format: 'DD.MM.YYYY'
                time_format: 'HH:mm'
                picker_utc: true
              - name: 'end'
                label: 'Data zakończenia'
                widget: 'datetime'
                default: ''
                date_format: 'DD.MM.YYYY'
                time_format: 'HH:mm'
                required: false
                picker_utc: true
